"""Add profile_image to CV

Revision ID: 6104f6581867
Revises: ac7b3eec10fe
Create Date: 2026-01-27 16:14:07.890193

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6104f6581867"
down_revision: str | Sequence[str] | None = "ac7b3eec10fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cvs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_image", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cvs", schema=None) as batch_op:
        batch_op.drop_column("profile_image")

    # ### end Alembic commands ###
